<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ $kind === 'sale' ? 'Fast Sales' : 'Fast Purchase' }} · zoloERP</title>
    <link rel="stylesheet" href="{{ asset('css/zolo-erp-neo.css') }}">
    <link rel="stylesheet" href="{{ asset('css/commercial-entry.css') }}">
    <script defer src="{{ asset('js/commercial-entry.js') }}"></script>
</head>
<body data-kind="{{ $kind }}" data-base="{{ url('/commercial/'.$kind) }}" data-compliance="{{ config('compliance.enabled') ? '1' : '0' }}" data-post-url="{{ isset($exchangeReturn) ? url('/compliance/exchange/'.$exchangeReturn->id) : '' }}">
<header class="topbar"><a href="{{ url('/dashboard') }}">zoloERP</a><span>Company {{ $context->companyId }} / Branch {{ $context->branchId }}</span><nav aria-label="Entry modes"><a href="{{ url('/commercial/sale/entry') }}">F2 Sales</a><a href="{{ url('/commercial/purchase/entry') }}">F12 Purchase</a></nav></header>
<main>
    <div class="heading"><div><p class="eyebrow">COUNTER ENTRY</p><h1>{{ $kind === 'sale' ? 'Fast Sales' : 'Fast Purchase' }}</h1></div><button type="button" id="restore-draft">Restore draft</button></div>
    <p id="status" role="status" aria-live="polite">Ready. Search a party, then add items.</p>
    @isset($exchangeReturn)<p class="panel">Exchange against return {{ $exchangeReturn->reference_no }}. Select the same customer and enter replacement items.</p>@endisset
    <form id="entry-form">
        <section class="panel fields" aria-label="Document details">
            <div class="search"><label for="party-search">{{ $kind === 'sale' ? 'Customer' : 'Supplier' }}</label><input id="party-search" autocomplete="off" placeholder="Name, city, alias or phone" aria-controls="party-results"><div id="party-results" class="results" aria-label="Party search results"></div><button type="button" data-inline="parties">New party · Alt+C</button></div>
            <label for="warehouse">Warehouse<select id="warehouse" required>@foreach($warehouses as $warehouse)<option value="{{ $warehouse->id }}">{{ $warehouse->name }}</option>@endforeach</select></label>
            <label for="business-date">Document date<input id="business-date" type="date" value="{{ $businessDate }}" required></label>
            @if($kind === 'purchase')<label for="receipt-status">Receipt status<select id="receipt-status"><option value="1">Received</option><option value="2">Partial</option><option value="3">Pending</option><option value="4">Unbilled order</option></select></label>@endif
            @if(config('compliance.enabled'))<label for="place-of-supply">Place of supply state code (optional)<input id="place-of-supply" maxlength="2" pattern="[0-9]{2}" placeholder="Party state"></label><label for="reverse-charge"><input id="reverse-charge" type="checkbox"> Reverse charge</label>@endif
        </section>
        <section class="hud" aria-label="Party balance"><div><span>Previous outstanding</span><strong id="previous">—</strong></div><div><span>Current invoice</span><strong id="current">0.0000</strong></div><div><span>Total to settle</span><strong id="combined">—</strong></div></section>
        @if($kind === 'sale')<p id="credit-summary" aria-live="polite">Select a customer to view overdue balance and available credit.</p>@endif
        <section class="panel" aria-label="Invoice items">
            <div class="search product-search"><label for="product-search">Add item</label><input id="product-search" autocomplete="off" placeholder="Item code or name; Enter to select" aria-controls="product-results"><div id="product-results" class="results" aria-label="Item search results"></div><button type="button" data-inline="products">New item · F6</button></div>
            <div class="table-scroll"><table><thead><tr><th scope="col">Item</th><th scope="col">Quantity</th><th scope="col">{{ $kind === 'sale' ? 'Net price' : 'Net cost' }}</th>@if($kind === 'purchase')<th scope="col">Received</th>@endif<th scope="col">Tracking</th><th scope="col">Actions</th></tr></thead><tbody id="item-lines"></tbody></table></div>
            <p id="empty-lines">No items yet. Enter an item code above.</p>
        </section>
        <details class="panel"><summary>Charges, discount and transport</summary><div class="fields">
            <label for="discount">Invoice discount<input id="discount" type="number" min="0" step="0.0001" value="0"></label><label for="freight">Freight<input id="freight" type="number" min="0" step="0.0001" value="0"></label>
            @if($kind === 'purchase')<label for="landed-method">Allocate freight<select id="landed-method"><option value="value">By value</option><option value="quantity">By quantity</option><option value="weight">By weight</option><option value="manual">Manual</option></select></label><label for="purchase-order">Purchase order ID (optional)<input id="purchase-order" type="number" min="1"></label><label for="receipt-number">Goods receipt number (optional)<input id="receipt-number" maxlength="100"></label><label for="update-cost"><input id="update-cost" type="checkbox"> Update item cost on save</label><label for="update-hsn"><input id="update-hsn" type="checkbox"> Update item HSN on save</label>@endif
            <label for="transport">Transport<input id="transport" maxlength="255"></label><label for="lr-number">LR number<input id="lr-number" maxlength="255"></label><label for="note">Note<textarea id="note" rows="2"></textarea></label>
        </div></details>
        <section class="panel fields" aria-label="Payment">
            <label for="paid">Initial payment<input id="paid" type="number" min="0" step="0.0001" value="0"></label><label for="method">Payment method<select id="method"><option>Cash</option><option>Bank</option><option>Cheque</option><option>Credit Card</option></select></label><label for="account">Payment account<select id="account">@foreach($accounts as $account)<option value="{{ $account->id }}">{{ $account->name }}</option>@endforeach</select></label>
            @if($kind === 'sale')<label for="override">Credit override reason (permission required)<input id="override" maxlength="500"></label>@endif
        </section>
        <footer class="actions"><span id="draft-status">Draft not saved</span><button type="button" id="save-draft">Save draft</button><button type="button" id="clone">Clone prior bill</button><button type="button" id="pending">Pending bills · Ctrl+B</button><button type="submit" class="primary" id="post">Post invoice · Ctrl+Enter</button></footer>
    </form>
    <p class="shortcuts">Space: party search · Enter: advance · Alt+C: new party · F6: new item · Ctrl+S: previous rates · Alt+Y: statement · Esc: close</p>
</main>
<dialog id="info-dialog"><div class="dialog-heading"><h2 id="info-title">Details</h2><button type="button" data-close aria-label="Close details">Close</button></div><div id="info-content"></div></dialog>
<dialog id="inline-dialog"><form id="inline-form"><div class="dialog-heading"><h2 id="inline-title">New master</h2><button type="button" data-close>Close</button></div><label for="master-name">Name<input id="master-name" name="name" required maxlength="100"></label><div id="party-fields"><label for="master-phone">Phone<input id="master-phone" name="phone_number"></label><label for="master-city">City<input id="master-city" name="city"></label><label for="master-alias">Search alias<input id="master-alias" name="search_alias" maxlength="100"></label><label for="master-address">Address<input id="master-address" name="address"></label>@if($kind === 'sale')<label for="master-credit-days">Credit days<input id="master-credit-days" name="credit_days" type="number" min="0" max="3650" value="0"></label><label for="master-credit-limit">Credit limit<input id="master-credit-limit" name="credit_limit" type="number" min="0" step="0.0001" value="0"></label><label for="master-group">Customer group<select id="master-group" name="customer_group_id">@foreach($groups as $group)<option value="{{ $group->id }}">{{ $group->name }}</option>@endforeach</select></label>@endif</div><div id="product-fields"><label for="master-code">Code<input id="master-code" name="code"></label><label for="master-category">Category<select id="master-category" name="category_id">@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select></label><label for="master-unit">Unit<select id="master-unit" name="unit_id">@foreach($units as $unit)<option value="{{ $unit->id }}">{{ $unit->unit_name }}</option>@endforeach</select></label><label for="master-price">Price<input id="master-price" name="price" type="number" min="0" step="0.0001" value="0"></label><label for="master-cost">Cost<input id="master-cost" name="cost" type="number" min="0" step="0.0001" value="0"></label></div><p id="inline-error" role="alert"></p><button class="primary" type="submit">Create and select</button></form></dialog>
<dialog id="tracking-dialog"><form id="tracking-form"><h2>Stock tracking and freight</h2><p>Enter the identities for this line. Stock rules validate these when posting.</p><label for="serials">Serials (comma separated)<textarea id="serials"></textarea></label><label for="batch-id">Existing batch ID<input id="batch-id" type="number" min="1"></label>@if($kind === 'purchase')<label for="batch-no">New batch number<input id="batch-no"></label><label for="expiry">Expiry date<input id="expiry" type="date"></label><label for="hsn-code">Item HSN<input id="hsn-code" inputmode="numeric" maxlength="8"></label><label for="weight">Line weight<input id="weight" type="number" min="0" step="0.0001"></label><label for="manual-freight">Manual freight allocation<input id="manual-freight" type="number" min="0" step="0.0001"></label><fieldset><legend>New dimensioned piece</legend><label for="piece-number">Piece number<input id="piece-number" maxlength="100"></label><div class="fields"><label for="piece-length">Length<input id="piece-length" type="number" min="0.000001" step="0.000001"></label><label for="piece-width">Width<input id="piece-width" type="number" min="0.000001" step="0.000001"></label><label for="piece-thickness">Thickness<input id="piece-thickness" type="number" min="0.000001" step="0.000001"></label></div></fieldset>@endif<label for="identity">Stock identity ID<input id="identity" type="number" min="1"></label><label for="variant">Variant ID<input id="variant" type="number" min="1"></label><button type="button" data-close>Cancel</button><button type="submit" class="primary">Apply</button></form></dialog>
</body>
</html>
