@extends('backend.operations.layout')
@section('title', ['manufacturing'=>'BOM & Production','job-work'=>'Job Work','profiles'=>'Business Profile','projects'=>'Sites & Projects','stock'=>'Stock Tools'][$area])
@section('content')
<div class="ops-heading"><div><p class="ops-eyebrow">{{ $profile['profile'] === 'general_trading' ? 'GENERAL TRADING' : strtoupper($profile['profile']) }}</p><h1>@yield('title')</h1></div><span class="ops-badge">{{ count($records) }} recent records</span></div>
@if(in_array($area, ['manufacturing','job-work','projects']))
<section class="ops-panel"><h2>Recent {{ $area === 'manufacturing' ? 'production orders' : ($area === 'job-work' ? 'orders' : 'projects') }}</h2>
<div class="ops-table-wrap"><table><thead><tr><th>Document</th><th>Status</th><th>{{ $area === 'manufacturing' ? 'Planned / completed' : 'Date' }}</th><th>Open</th></tr></thead><tbody>
@forelse($records as $record)<tr><td>{{ $record->reference_no ?? $record->title }}</td><td><span class="ops-badge">{{ $record->status }}</span></td><td>{{ $area === 'manufacturing' ? $record->planned_qty.' / '.$record->completed_qty : ($record->business_date ?? $record->start_date) }}</td><td><a href="{{ url('/operations/'.(['manufacturing'=>'production','job-work'=>'job-work','projects'=>'project'][$area]).'/'.$record->id) }}">Open</a></td></tr>@empty<tr><td colspan="4">No records yet. Create your first record below.</td></tr>@endforelse
</tbody></table></div></section>
@endif
@if($area === 'manufacturing')
@if($legacyProductions->isNotEmpty())<section class="ops-panel"><h2>Retained legacy production</h2><p>Historical records remain read-only. Review opening balances before linking them to normalized orders.</p><div class="ops-table-wrap"><table><thead><tr><th>Reference</th><th>Date</th><th>Status</th><th>Cost</th></tr></thead><tbody>@foreach($legacyProductions as $legacy)<tr><td>{{ $legacy->reference_no }}</td><td>{{ $legacy->created_at }}</td><td>{{ $legacy->status }}</td><td>{{ $legacy->total_cost }}</td></tr>@endforeach</tbody></table></div></section>@endif
<section class="ops-panel"><h2>Published BOM versions</h2><div class="ops-table-wrap"><table><thead><tr><th>Code</th><th>Version</th><th>Effective range</th><th>Output</th></tr></thead><tbody>@forelse($boms as $bom)<tr><td>{{ $bom->code }}</td><td>{{ $bom->version }}</td><td>{{ $bom->effective_from }} – {{ $bom->effective_to ?? 'Open' }}</td><td>{{ $products->firstWhere('id',$bom->product_id)?->name }} · {{ $bom->output_qty }}</td></tr>@empty<tr><td colspan="4">Create a BOM before planning production.</td></tr>@endforelse</tbody></table></div></section>
<section class="ops-panel"><h2>Create BOM version</h2><p>Each save publishes a new version. Published versions keep their original quantities and dates.</p>
@include('backend.operations.form_start', ['formId'=>'bom-form','action'=>'bom'])
<div class="ops-fields"><label>Output product<select name="product_id" required><option value="">Select product</option>@foreach($products->where('type','standard') as $product)<option value="{{ $product->id }}">{{ $product->name }}</option>@endforeach</select></label><label>BOM code<input name="code" maxlength="60" pattern="[A-Z0-9_-]+" required placeholder="RECIPE-01"></label><label>Output quantity<input name="output_qty" type="number" min="0.0001" step="0.0001" value="1" required></label><label>Output unit<select name="output_uom_id" required>@foreach($units as $unit)<option value="{{ $unit->id }}">{{ $unit->unit_name }}</option>@endforeach</select></label><label>Effective from<input name="effective_from" type="date" value="{{ $date }}" required></label><label>Effective to<input name="effective_to" type="date"></label>@include('backend.operations.date')</div>
<div class="ops-table-wrap"><table data-lines><thead><tr><th>Component</th><th>Quantity</th><th>Unit</th><th>Scrap %</th><th></th></tr></thead><tbody><tr data-line><td><label>Component<select name="lines[0][component_product_id]" required><option value="">Select component</option>@foreach($products->where('type','standard') as $product)<option value="{{ $product->id }}">{{ $product->name }}</option>@endforeach</select></label></td><td><label>Component quantity<input name="lines[0][qty]" type="number" step="0.0001" min="0.0001" required></label></td><td><label>Component unit<select name="lines[0][uom_id]" required>@foreach($units as $unit)<option value="{{ $unit->id }}">{{ $unit->unit_name }}</option>@endforeach</select></label></td><td><label>Scrap percent<input name="lines[0][scrap_percent]" type="number" step="0.0001" min="0" max="100" value="0" required></label></td><td><button type="button" data-remove-line>Remove</button></td></tr></tbody></table></div><button type="button" data-add-line>Add component</button><button type="submit" class="ops-primary">Publish BOM</button></form></section>
@if(in_array('manufacturing.production',$navigation))<section class="ops-panel"><h2>Plan production</h2>@include('backend.operations.form_start',['formId'=>'plan-form','action'=>'production-plan'])<div class="ops-fields"><label>BOM version<select name="bom_id" required><option value="">Select BOM</option>@foreach($boms as $bom)<option value="{{ $bom->id }}">{{ $bom->code }} · v{{ $bom->version }}</option>@endforeach</select></label>@include('backend.operations.warehouse')<label>Planned quantity<input name="planned_qty" type="number" step="0.0001" min="0.0001" required></label>@include('backend.operations.date')</div><button class="ops-primary">Plan production</button></form></section>@endif
@elseif($area === 'job-work')
<section class="ops-panel"><h2>Material outside</h2><div class="ops-table-wrap"><table><thead><tr><th>Order</th><th>Product</th><th>Pending quantity</th><th>Inventory value</th></tr></thead><tbody>@forelse($pending as $row)<tr><td>{{ $row['reference_no'] }}</td><td>{{ $products->firstWhere('id',$row['product_id'])?->name }}</td><td>{{ $row['pending_qty'] }}</td><td>{{ $row['pending_value'] }}</td></tr>@empty<tr><td colspan="4">No material pending outside.</td></tr>@endforelse</tbody></table></div></section>
<section class="ops-panel"><h2>Create Job Work order</h2>@include('backend.operations.form_start',['formId'=>'order-form','action'=>'job-order'])<div class="ops-fields"><label>Job worker<select name="job_worker_party_id" required><option value="">Select supplier</option>@foreach($suppliers as $supplier)<option value="{{ $supplier->id }}">{{ $supplier->name }}</option>@endforeach</select></label><label>Process<select name="process_type_id" required><option value="">Select process</option>@foreach($processes as $process)<option value="{{ $process->id }}">{{ $process->name }} · max loss {{ $process->max_loss_percent }}%</option>@endforeach</select></label>@include('backend.operations.date')<label>Expected return<input name="expected_return_date" type="date"></label><label>Notes<input name="notes" maxlength="5000"></label></div><button class="ops-primary">Create order</button></form></section>
<details class="ops-panel"><summary>Configure process</summary>@include('backend.operations.form_start',['formId'=>'process-form','action'=>'configure/process'])<div class="ops-fields"><label>Process code<input name="code" pattern="[A-Z0-9_-]+" maxlength="60" required></label><label>Name<input name="name" maxlength="100" required></label><label>Maximum loss (%)<input name="max_loss_percent" type="number" step="0.0001" min="0" max="100" value="0" required></label><label>Output behavior<select name="conversion"><option value="0">Return same material</option><option value="1">Convert to other products</option></select></label><label>Yield basis<select name="quantity_basis"><option value="base_qty">Base quantity</option><option value="volume_cbm">Volume (CBM)</option></select></label></div><button class="ops-primary">Save process</button></form></details>
@elseif($area === 'profiles')
<section class="ops-panel"><h2>Choose business profile</h2><p>Profile sets capabilities, labels and product attributes. Existing stock and accounting values stay unchanged.</p>
<div class="ops-profile-grid">@foreach(\App\Services\Industry\IndustryCatalog::SUBTYPES as $key=>$subtypes)<article class="ops-profile-card {{ $profile['profile'] === $key ? 'is-current' : '' }}"><h3>{{ \App\Services\Platform\CapabilityCatalog::PROFILES[$key][0] }}</h3><p>{{ implode(' · ',\App\Services\Industry\IndustryCatalog::SETTINGS[$key]['units']) }}</p>@include('backend.operations.form_start',['formId'=>'profile-'.$key,'action'=>'configure/profile'])<input type="hidden" name="profile" value="{{ $key }}"><label>Business subtype<select name="subtype">@foreach($subtypes as $subtype=>$features)<option value="{{ $subtype }}">{{ ucwords(str_replace('_',' ',$subtype)) }}</option>@endforeach</select></label><button class="ops-primary">{{ $profile['profile'] === $key ? 'Apply profile' : 'Choose profile' }}</button></form></article>@endforeach</div></section>
<section class="ops-panel"><h2>Product attributes</h2><label>Product<select id="attribute-product"><option value="">Select product</option>@foreach($products as $product)<option value="{{ $product->id }}">{{ $product->name }}</option>@endforeach</select></label><form id="attribute-form" class="ops-form"><div id="attribute-fields" class="ops-fields"></div><button type="submit" class="ops-primary" disabled>Save attributes</button></form><p id="attribute-status" role="status" aria-live="polite">Select a product to see enabled profile attributes.</p></section>
@elseif($area === 'projects')
<section class="ops-panel"><h2>Create site / project</h2>@include('backend.operations.form_start',['formId'=>'project-form','action'=>'project'])<div class="ops-fields"><label>Project name<input name="title" maxlength="191" required></label><label>Customer<select name="client_id" required><option value="">Select customer</option>@foreach($customers as $customer)<option value="{{ $customer->id }}">{{ $customer->name }}</option>@endforeach</select></label><label>Site address<input name="site_address" maxlength="2000" required></label><label>Contact<input name="contact" maxlength="255"></label><label>System size (kW)<input name="system_kw" type="number" min="0.001" step="0.001" required></label><label>Budget<input name="budget" type="number" min="0" step="0.01" value="0"></label>@include('backend.operations.date')<label>Site notes<textarea name="site_notes" maxlength="5000"></textarea></label></div><button class="ops-primary">Create project</button></form></section>
@elseif($area === 'stock')
@if($batchBalances)<section class="ops-panel"><h2>Batch expiry and MRP</h2><div class="ops-table-wrap"><table><thead><tr><th>Product</th><th>Warehouse</th><th>Batch</th><th>Expiry</th><th>MRP</th><th>Balance</th></tr></thead><tbody>@foreach($batchBalances as $balance)<tr><td>{{ $balance->product }}</td><td>{{ $balance->warehouse }}</td><td>{{ $balance->batch_no }}</td><td>{{ $balance->expired_date }}</td><td>{{ $balance->mrp }}</td><td>{{ $balance->qty }}</td></tr>@endforeach</tbody></table></div></section>@endif
<section class="ops-panel"><h2>Stock tools</h2><p>Batch, expiry and piece workflows appear when their capabilities are enabled.</p></section>
@if(in_array('inventory.batch_expiry',$navigation))<section class="ops-panel"><h2>Expired batch disposal</h2>@include('backend.operations.form_start',['formId'=>'expiry-form','action'=>'expiry-writeoff'])<div class="ops-fields">@include('backend.operations.warehouse')@include('backend.operations.date')<label>Reason<input name="reason" maxlength="500" required></label></div><div class="ops-table-wrap"><table data-lines><thead><tr><th>Product</th><th>Quantity</th><th>Unit</th><th>Batch / identity</th><th></th></tr></thead><tbody>@include('backend.operations.stock_line',['prefix'=>'lines[0]'])</tbody></table></div><button type="button" data-add-line>Add batch</button><button class="ops-primary">Post disposal</button></form></section>
<details class="ops-panel"><summary>Quantity scheme</summary>@include('backend.operations.form_start',['formId'=>'scheme-form','action'=>'configure/scheme'])<div class="ops-fields"><label>Product<select name="product_id" required>@foreach($products->where('type','standard') as $product)<option value="{{ $product->id }}">{{ $product->name }}</option>@endforeach</select></label><label>Name<input name="name" required maxlength="100" placeholder="10+1"></label><label>Buy quantity (base unit)<input name="buy_qty" type="number" min="0.0001" step="0.0001" value="10" required></label><label>Free quantity (base unit)<input name="free_qty" type="number" min="0.0001" step="0.0001" value="1" required></label><label>Valid from<input name="valid_from" type="date" value="{{ $date }}" required></label><label>Valid to<input name="valid_to" type="date" required></label></div><button class="ops-primary">Save scheme</button></form></details>@endif
@endif
@if($area === 'job-work')<section class="ops-panel"><h2>Job Work shrinkage</h2><div class="ops-table-wrap"><table><thead><tr><th>Receipt</th><th>Date</th><th>Received</th><th>Loss</th><th>Loss %</th></tr></thead><tbody>@forelse($shrinkage as $receipt)<tr><td>{{ $receipt->reference_no }}</td><td>{{ $receipt->business_date }}</td><td>{{ $receipt->details_json['received_qty'] }}</td><td>{{ $receipt->details_json['loss_qty'] }}</td><td>{{ $receipt->details_json['loss_percent'] }}</td></tr>@empty<tr><td colspan="5">No active receipts yet.</td></tr>@endforelse</tbody></table></div></section>@endif
@endsection
