@extends('backend.workspace.layout')
@section('title','Home')
@section('content')
<div class="ops-heading"><div><p class="ops-eyebrow">{{ $company->code }}</p><h1>{{ $company->trade_name ?: $company->legal_name }}</h1></div></div>
<section class="ops-panel"><h2>Active branch and financial year</h2><form method="post" action="/workspace/context">@csrf<input type="hidden" name="company_id" value="{{ $company->id }}"><div class="ops-fields"><label>Branch<select name="branch_id">@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected($branch->id === $context->branchId)>{{ $branch->name }}</option>@endforeach</select></label><label>Financial year<select name="financial_year_id">@foreach($years as $year)<option value="{{ $year->id }}" @selected($year->id === $context->financialYearId)>{{ $year->name }} · {{ $year->status }}</option>@endforeach</select></label></div><button class="ops-primary">Use selected context</button></form></section>
<section class="ops-panel"><h2>Workspaces</h2><div class="workspace-grid">@forelse($navigation as $item)<a class="workspace-card" href="{{ $item['url'] }}">{{ $item['label'] }}<span>Open workspace</span></a>@empty<p>Ask your company administrator to enable the workspaces your role needs.</p>@endforelse</div></section>
<section class="ops-panel"><h2>Other companies</h2>@foreach($choices as $choice)@if($choice['id'] !== $context->companyId)<details><summary>{{ $choice['legal_name'] }}</summary><form method="post" action="/workspace/context">@csrf<input type="hidden" name="company_id" value="{{ $choice['id'] }}"><div class="ops-fields"><label>Branch<select name="branch_id" required>@foreach($choice['branches'] as $branch)<option value="{{ $branch['id'] }}">{{ $branch['name'] }}</option>@endforeach</select></label><label>Financial year<select name="financial_year_id" required>@foreach($choice['years'] as $year)<option value="{{ $year['id'] }}">{{ $year['name'] }} · {{ $year['status'] }}</option>@endforeach</select></label></div><button class="ops-primary">Switch company</button></form></details>@endif
@endforeach</section>
@endsection
