@extends('backend.workspace.layout')
@section('title','Company setup')
@section('content')
<div class="ops-heading"><div><p class="ops-eyebrow">SETTINGS</p><h1>Company setup</h1><p>{{ $company['legal_name'] }}</p></div></div>
<section class="ops-panel"><h2>Business details</h2><form method="post" action="/workspace/setup/company?company_id={{ $company['id'] }}">@csrf<div class="ops-fields"><label>Legal name<input name="legal_name" value="{{ old('legal_name',$company['legal_name']) }}" required maxlength="255"></label><label>Trade name<input name="trade_name" value="{{ old('trade_name',$company['trade_name']) }}" maxlength="255"></label><label>State code<input name="state_code" value="{{ old('state_code',$company['state_code']) }}" required maxlength="20"></label><label>Currency<select name="base_currency_id" required>@foreach($currencies as $currency)<option value="{{ $currency->id }}" @selected($currency->id == $company['base_currency_id'])>{{ $currency->code }} · {{ $currency->name }}</option>@endforeach</select></label><label>Preferred print format<select name="print_format">@foreach(['a4'=>'A4','thermal'=>'Thermal','dot_matrix'=>'Dot Matrix'] as $key=>$label)<option value="{{ $key }}" @selected($print_format === $key)>{{ $label }}</option>@endforeach</select></label></div><button class="ops-primary">Save business details</button></form></section>
<section class="ops-panel"><h2>Financial years</h2><p>{{ count($years) }} configured. Closed years remain available for historical reads.</p><a href="/company/financial-years/setup?company_id={{ $company['id'] }}">Manage financial years</a></section>
<section class="ops-panel"><h2>Branches</h2><ul>@foreach($branches as $branch)<li>{{ $branch->name }}</li>@endforeach</ul><details><summary>Add branch</summary><form method="post" action="/workspace/setup/branch?company_id={{ $company['id'] }}">@csrf<div class="ops-fields"><label>Code<input name="code" pattern="[A-Z0-9_-]+" required maxlength="50"></label><label>Name<input name="name" required maxlength="255"></label></div><button class="ops-primary">Add branch</button></form></details></section>
<section class="ops-panel"><h2>Warehouses</h2><ul>@forelse($warehouses as $warehouse)<li>{{ $warehouse->name }}</li>@empty<li>Add a warehouse before receiving stock.</li>@endforelse</ul><details><summary>Add warehouse</summary><form method="post" action="/workspace/setup/warehouse?company_id={{ $company['id'] }}">@csrf<div class="ops-fields"><label>Branch<select name="branch_id" required>@foreach($branches as $branch)<option value="{{ $branch->id }}">{{ $branch->name }}</option>@endforeach</select></label><label>Name<input name="name" required maxlength="255"></label><label>Address<textarea name="address" required maxlength="1000"></textarea></label><label>Phone<input name="phone" maxlength="50"></label><label>Email<input name="email" type="email" maxlength="255"></label></div><button class="ops-primary">Add warehouse</button></form></details></section>
<section class="ops-panel"><h2>Business profile and capabilities</h2><p>Optional activation: {{ $activation_ready ? 'Foundation accepted' : 'Awaiting company isolation acceptance' }}.</p><p>Opening data and production activation require reconciliation and reviewed acceptance.</p><ul>@foreach($capabilities as $key=>$state)@if($state['enabled'])<li>{{ \App\Services\Platform\CapabilityCatalog::DEFINITIONS[$key][0] }}</li>@endif
@endforeach</ul><a href="/accounting/semantic-mappings">Account mappings</a></section>
@endsection
